title: Hello, world! First blog opened
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Yonggi Jeong # add your name
author-img: yonggi.jpg # add your photo
about-author: I am an AI developer focusing on computer vision. Always hungry to keep learning. # add description
social-twitter: # add your Twitter handle
social-facebook: 100001984981521 # add your Facebook handle
social-github: animilux # add your Github handle
social-linkedin: yonggi-jeong-9779351a8 # add your Linkedin handle
social-email: jok0905@naver.com # add your Email address

# Disqus
discus-identifier: bravery # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
